#!/bin/bash

dirpath=$1

if [ -z $dirpath ]; then
  echo "Please specify dirpath (arg 1)"
  exit 1
fi

mkdir -p $(pwd)/$dirpath

selfpath=$( cd "$( dirpath "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )

files=(a b c d e f)
for file in "${files[@]}"; do
  cp $selfpath/template.py $(pwd)/$dirpath/$file.py
done
