#!/bin/bash

filepath=$1

if [ -z $filepath ]; then
  echo "Please specify filepath (arg 1)"
  exit 1
fi

selfpath="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )" 

cp $selfpath/template.py $(pwd)/$filepath
